### ISSUE TITLE
Face Vertices Indices

### ISSUE THREAD

**Issue by Ghetz** [chrisjansson/ObjLoader#10]
Dear Chris

I'm able to access the raw obj model from the LoadResult class into another application for processing.
But the result does not contain the face vertices indices.
How do I read those please? My c# is not strong.

Many thanks,
Ghetz

**Comment by chrisjansson** [comment]
Hoi,

Face vertex indices are available on from the LoadResult type via Groups.

https://github.com/chrisjansson/ObjLoader/blob/master/source/CjClutter.ObjLoader.Loader/Data/Elements/Group.cs
https://github.com/chrisjansson/ObjLoader/blob/master/source/CjClutter.ObjLoader.Loader/Data/Elements/Face.cs

Hope that helps a bit, if not I'll explain it a bit more in depth.

Chris

**Comment by Ghetz** [comment]
Many thanks Chris.

It is working now - my initial arrays were wrong, corrected as so:

```
for (int i=0; i<result.Groups.Count;i++) //groups
                    {
                        // Array to hold face indices
                        int[,,] faceVertex = new int[result.Groups.Count,result.Groups[i].Faces.Count,9];

                        for(int j=0;j<result.Groups[i].Faces.Count; j++) //faces
                        {
                            for(int k=0;k<9; k++) //face vertex
                            {
                                switch (k)
                                {
                                    case 0:
                                    faceVertex[i,j,k] = result.Groups[i].Faces[j][k].VertexIndex;;
                                    break;
                                    ...
                                }
                            }
                        }
                    }
```

**Comment by chrisjansson** [comment]
Great!
