### ISSUE TITLE
Add licence information

### ISSUE THREAD

**Issue by ERS-EIT** [chrisjansson/ObjLoader#11]
Pleased tell us the licence type for this code. Can we use it in own projects without mentioning you? Can we even sell our product containing your code?

**Comment by chrisjansson** [comment]
Hi,

In short, you're free to use it commercially. The included license and copyright notice must however be kept.

Have a look at the included license.md in the root of the repository.
https://github.com/chrisjansson/ObjLoader/blob/master/LICENSE.md
