### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by avarisc** [ChrisJansson/ObjLoader#4]
I can't find any indication of what licensing this is provided under.  I do hope I've not simply missed it somehow.  Without license, from my understanding, I am to assume I do not have permission to use it.  Can someone point me in the right direction, or clarify the license of this project?

**Comment by ChrisJansson** [comment]
I just haven't added a license. :smile: I'll do that later today. I'll put it under a MIT license so the intention is free of course. 

I publish my code with the understanding that if it lacks license it's completely free. 

Cheers

**Comment by ChrisJansson** [comment]
Having looked at Githubs disclaimer for license less projects your understanding was correct actually.

I've added a license for the code now any way.
