### ISSUE TITLE
Help with providing own material stream provider

### ISSUE THREAD

**Issue by Ghetz** [chrisjansson/ObjLoader#7]
Hello,

I'm a beginner in C# programming.

I'm trying to point the material stream provider to a directory containing my obj file by:
`Func<string, Stream> getStream = GetFileStream;`

//where GetFileStream is:
`private static Stream GetFileStream(string myObjFilePath)
        {
            using(Stream sr = File.Open(myObjFilePath, FileMode.Create))
            {
                return sr;
            }
       }`

`var objLoaderFactory = new `ObjLoaderFactory();`

//but I'm stuck as to what to do here:
`var objLoader = objLoaderFactory.Create(materialFileName => File.Open(materialFileName);`

Many thanks,
ghetz

**Comment by chrisjansson** [comment]
Hey,

I can see why you'd have problems doing it that way, I've apparently updated the code and not the example.

The way you have to do it is something like this:

```
public class MaterialStreamProvider : IMaterialStreamProvider
{
    public Stream Open(string materialFilePath) 
    {
        var directoryPath = ...;
        var path = Path.Combine(directoryPath, materialFilePath);
        return File.Open(path);
    }
}
```

**Comment by Ghetz** [comment]
Hello Chris,

Many thanks for taking the time to point me in the right direction.
Will try your suggestion asap. 

Cheers,
Ghetz

**Comment by chrisjansson** [comment]
Any progress?

**Comment by Ghetz** [comment]
Dear Chris,
My apologies for the very very late reply. Yes, it did work.

Many thanks,
Ghetz

**Comment by chrisjansson** [comment]
Great 👍
